// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectroPoint.Migrations
{
    [DbContext(typeof(EletroPointDbContext))]
    partial class EletroPointDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectroPoint.Models.AdminModel", b =>
                {
                    b.Property<int>("Id_admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_admin"));

                    b.Property<decimal>("Cpf")
                        .HasColumnType("decimal(11,0)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Funcao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("bit");

                    b.HasKey("Id_admin");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("ElectroPoint.Models.CarrinhoModel", b =>
                {
                    b.Property<int>("Id_carrinho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_carrinho"));

                    b.Property<DateTime>("Hora_da_cricao")
                        .HasPrecision(0)
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Itens")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Quantidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id_carrinho");

                    b.HasIndex("UserId");

                    b.ToTable("Carrinho", (string)null);
                });

            modelBuilder.Entity("ElectroPoint.Models.EletronicosModel", b =>
                {
                    b.Property<int>("Id_eletronicos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_eletronicos"));

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<int?>("MarcaModelId_marca")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_eletronicos");

                    b.HasIndex("MarcaId");

                    b.HasIndex("MarcaModelId_marca");

                    b.ToTable("Eletronicos", (string)null);
                });

            modelBuilder.Entity("ElectroPoint.Models.MarcaModel", b =>
                {
                    b.Property<int>("Id_marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_marca"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id_marca");

                    b.ToTable("Marcas", (string)null);
                });

            modelBuilder.Entity("ElectroPoint.Models.UserModel", b =>
                {
                    b.Property<int>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_user"));

                    b.Property<decimal?>("Cpf")
                        .HasColumnType("decimal(11,0)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Funcao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Senha")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id_user");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ElectroPoint.Models.CarrinhoModel", b =>
                {
                    b.HasOne("ElectroPoint.Models.UserModel", "Usuario")
                        .WithMany("Carrinhos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ElectroPoint.Models.EletronicosModel", b =>
                {
                    b.HasOne("ElectroPoint.Models.MarcaModel", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectroPoint.Models.MarcaModel", null)
                        .WithMany("Eletronicos")
                        .HasForeignKey("MarcaModelId_marca");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ElectroPoint.Models.MarcaModel", b =>
                {
                    b.Navigation("Eletronicos");
                });

            modelBuilder.Entity("ElectroPoint.Models.UserModel", b =>
                {
                    b.Navigation("Carrinhos");
                });
#pragma warning restore 612, 618
        }
    }
}
